name: CI/CD for Multi-App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-app-x:
    if: contains(github.event.head_commit.modified, 'app-x/') || contains(github.event.head_commit.added, 'app-x/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for App X
        run: |
          cd app-x
          docker build -t hoangvangioi/app-x:latest .
          docker push hoangvangioi/app-x:latest

      - name: Deploy App X to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull and run new container for App X
            sudo docker pull hoangvangioi/app-x:latest
            sudo docker stop app-x || true
            sudo docker rm app-x || true
            sudo docker run --name app-x \
              -p 8080:8080 \
              --restart unless-stopped \
              -d hoangvangioi/app-x:latest

  build-and-deploy-app-y:
    if: contains(github.event.head_commit.modified, 'app-y/') || contains(github.event.head_commit.added, 'app-y/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for App Y
        run: |
          cd app-y
          docker build -t hoangvangioi/app-y:latest .
          docker push hoangvangioi/app-y:latest

      - name: Deploy App Y to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull and run new container for App Y
            sudo docker pull hoangvangioi/app-y:latest
            sudo docker stop app-y || true
            sudo docker rm app-y || true
            sudo docker run --name app-y \
              -p 8081:8081 \
              --restart unless-stopped \
              -d hoangvangioi/app-y:latest